## YAML Template.
---

server: 
    port: 8585
jc:
    jwt:
        security:
            enabled: true
        timezone: "America/Bogota"
        issuer: "www.progrmacionfacil.net"
        token:
            auth:
                path: "/v1.0/oauth/client_credential/accesstoken"
            secret: "Curso de Spring security"
            expires-in: 3600 # seconds
        excluded:
            path: "/v1.0/multi,/v1.0/otraexclusion" 

                    